version: "3"
services:
  keycloak:
    image: jboss/keycloak:9.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/tmp/example-realm.json
    volumes:
      - ./oauth2-sample-realm-config.json:/tmp/example-realm.json
    ports:
      # -Djboss.socket.binding.port-offset=10
      - "8090:8080"
